const {
  // updateEveryMs
  REACT_APP_DEFAULT_UPDATE_EVERY_MS,
  REACT_APP_STEP_UPDATE_EVERY_MS,
  REACT_APP_MAX_UPDATE_EVERY_MS,
  REACT_APP_MIN_UPDATE_EVERY_MS,
  // cellSize
  REACT_APP_DEFAULT_CELL_SIZE,
  REACT_APP_MIN_CELL_SIZE,
  REACT_APP_MAX_CELL_SIZE,
  REACT_APP_STEP_CELL_SIZE,
} = process.env;

export const DEFAULT_UPDATE_EVERY_MS: number = +REACT_APP_DEFAULT_UPDATE_EVERY_MS!;
export const STEP_UPDATE_EVERY_MS: number = +REACT_APP_STEP_UPDATE_EVERY_MS!;
export const MAX_UPDATE_EVERY_MS: number = +REACT_APP_MAX_UPDATE_EVERY_MS!;
export const MIN_UPDATE_EVERY_MS: number = +REACT_APP_MIN_UPDATE_EVERY_MS!;
export const DEFAULT_CELL_SIZE: number = +REACT_APP_DEFAULT_CELL_SIZE!;
export const MIN_CELL_SIZE: number = +REACT_APP_MIN_CELL_SIZE!;
export const MAX_CELL_SIZE: number = +REACT_APP_MAX_CELL_SIZE!;
export const STEP_CELL_SIZE: number = +REACT_APP_STEP_CELL_SIZE!;
